export default class PokemonGo {
  static WEAKNESSES = {
    NORMAL: ['FIGHTING'],
    FIRE: ['WATER', 'GROUND', 'ROCK'],
    WATER: ['ELECTRIC', 'GRASS'],
    ELECTRIC: ['GROUND'],
    GRASS: ['FIRE', 'ICE', 'POISON', 'FLYING', 'BUG'],
    ICE: ['FIRE', 'FIGHTING', 'ROCK', 'STEEL'],
    FIGHTING: ['FLYING', 'PSYCHIC', 'FAIRY'],
    POISON: ['GROUND', 'PSYCHIC'],
    GROUND: ['WATER', 'GRASS', 'ICE'],
    FLYING: ['ELECTRIC', 'ICE', 'ROCK'],
    PSYCHIC: ['BUG', 'GHOST', 'DARK'],
    BUG: ['FIRE', 'FLYING', 'ROCK'],
    ROCK: ['WATER', 'GRASS', 'FIGHTING', 'GROUND', 'STEEL'],
    GHOST: ['GHOST', 'DARK'],
    DRAGON: ['ICE', 'DRAGON', 'FAIRY'],
    DARK: ['FIGHTING', 'BUG', 'FAIRY'],
    STEEL: ['FIRE', 'FIGHTING', 'GROUND'],
    FAIRY: ['POISON', 'STEEL'],
  };

  static RESISTANCES = {
    NORMAL: [],
    FIRE: ['FIRE', 'GRASS', 'ICE', 'BUG', 'STEEL', 'FAIRY'],
    WATER: ['FIRE', 'WATER', 'ICE', 'STEEL'],
    ELECTRIC: ['ELECTRIC', 'FLYING', 'STEEL'],
    GRASS: ['WATER', 'ELECTRIC', 'GRASS', 'GROUND'],
    ICE: ['ICE'],
    FIGHTING: ['BUG', 'ROCK', 'DARK'],
    POISON: ['GRASS', 'FIGHTING', 'POISON', 'BUG', 'FAIRY'],
    GROUND: ['POISON', 'ROCK'],
    FLYING: ['GRASS', 'FIGHTING', 'BUG'],
    PSYCHIC: ['FIGHTING', 'PSYCHIC'],
    BUG: ['GRASS', 'FIGHTING', 'GROUND'],
    ROCK: ['NORMAL', 'FIRE', 'POISON', 'FLYING'],
    GHOST: ['POISON', 'BUG'],
    DRAGON: ['FIRE', 'WATER', 'ELECTRIC', 'GRASS'],
    DARK: ['GHOST', 'DARK'],
    STEEL: [
      'NORMAL',
      'GRASS',
      'ICE',
      'FLYING',
      'PSYCHIC',
      'BUG',
      'ROCK',
      'DRAGON',
      'STEEL',
      'FAIRY',
    ],
    FAIRY: ['FIGHTING', 'BUG', 'DARK'],
  };

  static IMMUNITIES = {
    NORMAL: ['GHOST'],
    FIRE: [],
    WATER: [],
    ELECTRIC: [],
    GRASS: [],
    ICE: [],
    FIGHTING: [],
    POISON: [],
    GROUND: ['ELECTRIC'],
    FLYING: ['GROUND'],
    PSYCHIC: [],
    BUG: [],
    ROCK: [],
    GHOST: ['NORMAL', 'FIGHTING'],
    DRAGON: [],
    DARK: ['PSYCHIC'],
    STEEL: ['POISON'],
    FAIRY: ['DRAGON'],
  };

  constructor() {}
}
